### ISSUE TITLE
Is linux supported?

### ISSUE THREAD

**Issue by FZGabriel** [usnistgov/labbench#4]
I'm trying to use this module on Linux.
Is this possible that labbench only supports Windows?

Using the python REPL:
```python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import labbench
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gab/.local/lib/python3.10/site-packages/labbench/__init__.py", line 45, in <module>
    from ._backends import (
  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_backends.py", line 1301, in <module>
    class Win32ComDevice(Device, concurrency=True):
  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_device.py", line 333, in __init_subclass__
    cls.__imports__()
  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_backends.py", line 1322, in __imports__
    import win32com
ModuleNotFoundError: No module named 'win32com'
```

Best,
Gabriel

**Comment by dgkuester** [comment]
Hi Gabriel,

It looks like you've uncovered a bug - this shouldn't be a required dependency of labbench. I'm hoping this will be a quick fix that I can address in the coming days.

Sincerely,
Dan

From: Gabriel ***@***.***>
Sent: Wednesday, January 25, 2023 9:00 AM
To: usnistgov/labbench ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/labbench] Is linux supported? (Issue #4)


I'm trying to use this module on Linux.
Is this possible that labbench only supports Windows?

Using the python REPL:

Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import labbench

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/home/gab/.local/lib/python3.10/site-packages/labbench/__init__.py", line 45, in <module>

    from ._backends import (

  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_backends.py", line 1301, in <module>

    class Win32ComDevice(Device, concurrency=True):

  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_device.py", line 333, in __init_subclass__

    cls.__imports__()

  File "/home/gab/.local/lib/python3.10/site-packages/labbench/_backends.py", line 1322, in __imports__

    import win32com

ModuleNotFoundError: No module named 'win32com'

Best,
Gabriel

-

**Comment by FZGabriel** [comment]
Hi @dgkuester,

Thanks for your rapid answer.
Have a great day.

**Comment by dgkuester** [comment]
Hi @FZGabriel, 

I've pushed a new version 0.23.4 to pypi with a fix that corrected the issue on a machine running a recent Ubuntu install. Can you try the install again and see if it's fixed for you too?

**Comment by dgkuester** [comment]
Fixed in 0.23.4

**Comment by FZGabriel** [comment]
Thanks for your work @dgkuester!
